# -*- coding: utf-8 -*-
"""austin_animal_center.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ANAsHM9WF1DilINvXojaeoq-E-TCtzp
"""

import pandas
import matplotlib.pyplot as plt

table = pandas.read_csv("/austin_animal_center_stray_map.csv")

"""This project analyzes data from the Austin Animal Center.
The dataset shows information about animals - id, breed, sex, age and so on.
"""

table['Type'].value_counts()

"""This code gives us information about how many cats and dogs are in the animal center."""

table['Type'].value_counts().plot(kind='pie', title='Animals by Type')

"""This is a pie chart which shows us a visual representation of how many cats and dogs are in the animal center.

Conclusion:
- Cats are more than dogs in this animal center
"""

table['Age'].value_counts()

"""This code gives us information about how many animals are a specific age."""

table['Age'].value_counts().head(10).plot(kind='line', title='Most Common Ages')

"""This is a line chart which shows us a visual representation of the most common ages among the animals in the shelter.

Conclusion:
- Most of the animals in the center are young - between 1 and 3 years old.
"""

table['Type'].value_counts().plot(kind='bar', title='Animals by Type')
plt.title('Animals by Title')
plt.xlabel('Animal Type')
plt.ylabel('Count')
plt.show()

"""This is a bar chart which shows us a visual representation of how many dogs and cats are in the animal center. Here, we use matplotlib for better visualization."""

table['Color'].value_counts()

"""This code gives us information about how many animals are a specific color."""

table['Color'].value_counts().head(5).plot(kind='barh', title='Animals by Color')
plt.title('Animals by Title')
plt.xlabel('Animal Color')
plt.ylabel('Count')
plt.show()

"""This is a barh chart which shows us a visual representation of the 5 most common colors among animals in the center.

Conclusion:
- Most of the animals are color 'Brown Tabby', followed by 'Black/White', 'Torbie/White', 'Black' and 'Orange Tabby'
"""